name: Deploy Web
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Generate timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +%s)"

      - name: Install root dependencies
        run: npm install

      - name: Generate web data
        run: node scripts/generate-web-data.js

      - name: Install web dependencies
        run: npm install --prefix web

      - name: Build web application
        run: npm run build --prefix web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web/out
          publish_branch: gh-pages
          destination_dir: previews/${{ github.ref_name }}-${{ steps.timestamp.outputs.timestamp }}
          keep_files: true
